--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-06 21:56:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 17235)
-- Name: Events; Type: TABLE; Schema: public; Owner: miv
--

CREATE TABLE public."Events" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Date" timestamp without time zone NOT NULL,
    "CreatedBy" integer NOT NULL
);


ALTER TABLE public."Events" OWNER TO miv;

--
-- TOC entry 222 (class 1259 OID 17234)
-- Name: Events_Id_seq; Type: SEQUENCE; Schema: public; Owner: miv
--

ALTER TABLE public."Events" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Events_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 17214)
-- Name: Roles; Type: TABLE; Schema: public; Owner: miv
--

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Roles" OWNER TO miv;

--
-- TOC entry 218 (class 1259 OID 17213)
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: public; Owner: miv
--

ALTER TABLE public."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17248)
-- Name: UserEvents; Type: TABLE; Schema: public; Owner: miv
--

CREATE TABLE public."UserEvents" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "EventId" integer NOT NULL
);


ALTER TABLE public."UserEvents" OWNER TO miv;

--
-- TOC entry 224 (class 1259 OID 17247)
-- Name: UserEvents_Id_seq; Type: SEQUENCE; Schema: public; Owner: miv
--

ALTER TABLE public."UserEvents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserEvents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17222)
-- Name: Users; Type: TABLE; Schema: public; Owner: miv
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Email" text NOT NULL,
    "RoleId" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO miv;

--
-- TOC entry 220 (class 1259 OID 17221)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: miv
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 17208)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: miv
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO miv;

--
-- TOC entry 4930 (class 0 OID 17235)
-- Dependencies: 223
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: miv
--

COPY public."Events" ("Id", "Title", "Description", "Date", "CreatedBy") FROM stdin;
7	КупитьБамбук	КупитьБамбук	2025-03-29 12:55:00	1
\.


--
-- TOC entry 4926 (class 0 OID 17214)
-- Dependencies: 219
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: miv
--

COPY public."Roles" ("Id", "Name") FROM stdin;
1	Admin
2	User
\.


--
-- TOC entry 4932 (class 0 OID 17248)
-- Dependencies: 225
-- Data for Name: UserEvents; Type: TABLE DATA; Schema: public; Owner: miv
--

COPY public."UserEvents" ("Id", "UserId", "EventId") FROM stdin;
13	2	7
17	1	7
\.


--
-- TOC entry 4928 (class 0 OID 17222)
-- Dependencies: 221
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: miv
--

COPY public."Users" ("Id", "Username", "PasswordHash", "Email", "RoleId") FROM stdin;
1	Miv	$2a$11$Yl71yfsKbfx8owumSRTtceb2b4BQ4u22B99zrjXRve41Xs1nMALQC		1
2	Игнат	$2a$11$7.VZxqyPUbdnLPXknmP.pu1p/YJ4ecBKempZXFOTvgalyQwYa7eTe	mailmail@gmail.com	2
\.


--
-- TOC entry 4924 (class 0 OID 17208)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: miv
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250324180657_migration1	9.0.3
20250324180754_migration2	9.0.3
\.


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 222
-- Name: Events_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: miv
--

SELECT pg_catalog.setval('public."Events_Id_seq"', 8, true);


--
-- TOC entry 4939 (class 0 OID 0)
-- Dependencies: 218
-- Name: Roles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: miv
--

SELECT pg_catalog.setval('public."Roles_Id_seq"', 3, false);


--
-- TOC entry 4940 (class 0 OID 0)
-- Dependencies: 224
-- Name: UserEvents_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: miv
--

SELECT pg_catalog.setval('public."UserEvents_Id_seq"', 17, true);


--
-- TOC entry 4941 (class 0 OID 0)
-- Dependencies: 220
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: miv
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 2, true);


--
-- TOC entry 4770 (class 2606 OID 17241)
-- Name: Events PK_Events; Type: CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "PK_Events" PRIMARY KEY ("Id");


--
-- TOC entry 4764 (class 2606 OID 17220)
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- TOC entry 4774 (class 2606 OID 17252)
-- Name: UserEvents PK_UserEvents; Type: CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."UserEvents"
    ADD CONSTRAINT "PK_UserEvents" PRIMARY KEY ("Id");


--
-- TOC entry 4767 (class 2606 OID 17228)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4762 (class 2606 OID 17212)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4768 (class 1259 OID 17263)
-- Name: IX_Events_CreatedBy; Type: INDEX; Schema: public; Owner: miv
--

CREATE INDEX "IX_Events_CreatedBy" ON public."Events" USING btree ("CreatedBy");


--
-- TOC entry 4771 (class 1259 OID 17264)
-- Name: IX_UserEvents_EventId; Type: INDEX; Schema: public; Owner: miv
--

CREATE INDEX "IX_UserEvents_EventId" ON public."UserEvents" USING btree ("EventId");


--
-- TOC entry 4772 (class 1259 OID 17265)
-- Name: IX_UserEvents_UserId; Type: INDEX; Schema: public; Owner: miv
--

CREATE INDEX "IX_UserEvents_UserId" ON public."UserEvents" USING btree ("UserId");


--
-- TOC entry 4765 (class 1259 OID 17266)
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: miv
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- TOC entry 4776 (class 2606 OID 17242)
-- Name: Events FK_Events_Users_CreatedBy; Type: FK CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "FK_Events_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4777 (class 2606 OID 17253)
-- Name: UserEvents FK_UserEvents_Events_EventId; Type: FK CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."UserEvents"
    ADD CONSTRAINT "FK_UserEvents_Events_EventId" FOREIGN KEY ("EventId") REFERENCES public."Events"("Id") ON DELETE CASCADE;


--
-- TOC entry 4778 (class 2606 OID 17258)
-- Name: UserEvents FK_UserEvents_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."UserEvents"
    ADD CONSTRAINT "FK_UserEvents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4775 (class 2606 OID 17229)
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: miv
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE;


-- Completed on 2025-04-06 21:56:49

--
-- PostgreSQL database dump complete
--

